-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 12:04:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema technovert_institute_of_technology
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technovert_institute_of_technology
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technovert_institute_of_technology` DEFAULT CHARACTER SET utf8 ;
USE `technovert_institute_of_technology` ;

-- -----------------------------------------------------
-- Table `technovert_institute_of_technology`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovert_institute_of_technology`.`subject` (
  `SubjectID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SubjectName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`SubjectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technovert_institute_of_technology`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovert_institute_of_technology`.`teacher` (
  `TeacherID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `SubjectID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`TeacherID`),
  INDEX `fk_teacher_subject_idx` (`SubjectID` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_subject`
    FOREIGN KEY (`SubjectID`)
    REFERENCES `technovert_institute_of_technology`.`subject` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technovert_institute_of_technology`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovert_institute_of_technology`.`class` (
  `ClassID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ClassNumber` TINYINT UNSIGNED NOT NULL,
  `TeacherID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ClassID`),
  INDEX `fk_class_teacher1_idx` (`TeacherID` ASC) VISIBLE,
  CONSTRAINT `fk_class_teacher1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `technovert_institute_of_technology`.`teacher` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technovert_institute_of_technology`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovert_institute_of_technology`.`student` (
  `StudentID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Gender` ENUM("Male", "Female", "Other") NULL,
  `ClassID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `fk_student_class1_idx` (`ClassID` ASC) VISIBLE,
  CONSTRAINT `fk_student_class1`
    FOREIGN KEY (`ClassID`)
    REFERENCES `technovert_institute_of_technology`.`class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technovert_institute_of_technology`.`period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovert_institute_of_technology`.`period` (
  `PeriodID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `ClassID` TINYINT UNSIGNED NOT NULL,
  `TeacherID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`PeriodID`),
  INDEX `fk_period_class1_idx` (`ClassID` ASC) VISIBLE,
  INDEX `fk_period_teacher1_idx` (`TeacherID` ASC) VISIBLE,
  CONSTRAINT `fk_period_class1`
    FOREIGN KEY (`ClassID`)
    REFERENCES `technovert_institute_of_technology`.`class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_period_teacher1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `technovert_institute_of_technology`.`teacher` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technovert_institute_of_technology`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technovert_institute_of_technology`.`attendance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `StudentID` TINYINT UNSIGNED NOT NULL,
  `PeriodID` TINYINT UNSIGNED NOT NULL,
  `IsPresent` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendance_student1_idx` (`StudentID` ASC) VISIBLE,
  INDEX `fk_attendance_period1_idx` (`PeriodID` ASC) VISIBLE,
  CONSTRAINT `fk_attendance_student1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `technovert_institute_of_technology`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_period1`
    FOREIGN KEY (`PeriodID`)
    REFERENCES `technovert_institute_of_technology`.`period` (`PeriodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
