-- MySQL Script generated by MySQL Workbench
-- Mon Mar  7 19:42:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema technovert-cup-cricket-tournament
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technovert-cup-cricket-tournament
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technovert-cup-cricket-tournament` DEFAULT CHARACTER SET utf8 ;
USE `technovert-cup-cricket-tournament` ;

-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`player` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`player` (
  `PlayerID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Role` ENUM('Batter', 'Bowler', 'Keeper') NOT NULL,
  `TeamID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PlayerID`),
  INDEX `fk_team_player_PlayerID` (`TeamID` ASC) VISIBLE,
  CONSTRAINT `fk_player_team`
    FOREIGN KEY (`TeamID`)
    REFERENCES `technovert-cup-cricket-tournament`.`team` (`TeamID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`team` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`team` (
  `TeamID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TeamName` VARCHAR(50) NOT NULL,
  `CaptainID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`TeamID`),
  UNIQUE INDEX `CaptainID_UNIQUE` (`CaptainID` ASC) VISIBLE,
  CONSTRAINT `fk_player_team_CaptainID`
    FOREIGN KEY (`CaptainID`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`match` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`match` (
  `MatchID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Team1ID` INT UNSIGNED NOT NULL,
  `Team2ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MatchID`),
  INDEX `fk_team_match_Team1_idx` (`Team1ID` ASC) VISIBLE,
  INDEX `fk_team_match_Team2_idx` (`Team2ID` ASC) VISIBLE,
  CONSTRAINT `fk_team_match_Team1`
    FOREIGN KEY (`Team1ID`)
    REFERENCES `technovert-cup-cricket-tournament`.`team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_match_Team2`
    FOREIGN KEY (`Team2ID`)
    REFERENCES `technovert-cup-cricket-tournament`.`team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`batterStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`batterstatus` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`batterstatus` (
	`StatusID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `Status` varchar(30) NOT NULL,
    PRIMARY KEY (`StatusID`)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

INSERT INTO `technovert-cup-cricket-tournament`.`batterstatus` (`Status`) VALUES 
('Not Out'), ('Run Out'), ('Caught'), ('Bowled'), ('Stump Out');

-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`score` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`score` (
  `ScoreID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MatchID` INT UNSIGNED NOT NULL,
  `PlayerID` INT UNSIGNED NOT NULL,
  `Score` INT UNSIGNED NOT NULL,
  `StatusID` INT UNSIGNED NOT NULL,
  `OutBy` INT UNSIGNED NULL,
  `Bowler` INT UNSIGNED NULL,
  PRIMARY KEY (`ScoreID`),
  INDEX `MatchID` (`MatchID` ASC) VISIBLE,
  INDEX `PlayerID` (`PlayerID` ASC) VISIBLE,
  INDEX `StatusID` (`StatusID` ASC) VISIBLE,
  INDEX `OutBy` (`OutBy` ASC) VISIBLE,
  INDEX `Bowler` (`Bowler` ASC) VISIBLE,
  CONSTRAINT `fk_match_score_MatchID`
    FOREIGN KEY (`MatchID`)
    REFERENCES `technovert-cup-cricket-tournament`.`match` (`MatchID`),
  CONSTRAINT `fk_player_score_PlayerID`
    FOREIGN KEY (`PlayerID`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`),
  CONSTRAINT `fk_batterStatus_Score_StatusID`
	FOREIGN KEY (`StatusID`)
    REFERENCES `technovert-cup-cricket-tournament`.`batterStatus` (`StatusID`),
  CONSTRAINT `fk_player_score_OutBy`
    FOREIGN KEY (`OutBy`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`),
  CONSTRAINT `fk_player_score_Bowler`
    FOREIGN KEY (`Bowler`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
