-- MySQL Script generated by MySQL Workbench
-- Mon Mar  7 19:42:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema technovert-cup-cricket-tournament
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technovert-cup-cricket-tournament
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technovert-cup-cricket-tournament` DEFAULT CHARACTER SET utf8 ;
USE `technovert-cup-cricket-tournament` ;

-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`player` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`player` (
  `PlayerID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Position` ENUM('Batter', 'Bowler', 'Keeper') NOT NULL,
  `TeamID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`PlayerID`),
  INDEX `fk_player_team` (`TeamID` ASC) VISIBLE,
  CONSTRAINT `fk_player_team`
    FOREIGN KEY (`TeamID`)
    REFERENCES `technovert-cup-cricket-tournament`.`team` (`TeamID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`team` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`team` (
  `TeamID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TeamName` VARCHAR(50) NOT NULL,
  `CaptainID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`TeamID`),
  UNIQUE INDEX `CaptainID_UNIQUE` (`CaptainID` ASC) VISIBLE,
  CONSTRAINT `team_ibfk_1`
    FOREIGN KEY (`CaptainID`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`match` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`match` (
  `MatchID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Team1ID` TINYINT UNSIGNED NOT NULL,
  `Team2ID` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`MatchID`),
  INDEX `fk_match_team1_idx` (`Team1ID` ASC) VISIBLE,
  INDEX `fk_match_team2_idx` (`Team2ID` ASC) VISIBLE,
  CONSTRAINT `fk_match_team1`
    FOREIGN KEY (`Team1ID`)
    REFERENCES `technovert-cup-cricket-tournament`.`team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_team2`
    FOREIGN KEY (`Team2ID`)
    REFERENCES `technovert-cup-cricket-tournament`.`team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `technovert-cup-cricket-tournament`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `technovert-cup-cricket-tournament`.`score` ;

CREATE TABLE IF NOT EXISTS `technovert-cup-cricket-tournament`.`score` (
  `MatchID` TINYINT UNSIGNED NOT NULL,
  `PlayerID` TINYINT UNSIGNED NOT NULL,
  `Score` INT UNSIGNED NOT NULL,
  `Status` ENUM('Not Out', 'Run Out', 'Caught', 'Bowled', 'Stump Out') NOT NULL DEFAULT 'Not Out',
  `OutBy` TINYINT UNSIGNED NOT NULL,
  `Bowler` TINYINT UNSIGNED NOT NULL,
  INDEX `MatchID` (`MatchID` ASC) VISIBLE,
  INDEX `PlayerID` (`PlayerID` ASC) VISIBLE,
  INDEX `OutBy` (`OutBy` ASC) VISIBLE,
  INDEX `Bowler` (`Bowler` ASC) VISIBLE,
  CONSTRAINT `score_ibfk_1`
    FOREIGN KEY (`MatchID`)
    REFERENCES `technovert-cup-cricket-tournament`.`match` (`MatchID`),
  CONSTRAINT `score_ibfk_2`
    FOREIGN KEY (`PlayerID`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`),
  CONSTRAINT `score_ibfk_3`
    FOREIGN KEY (`OutBy`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`),
  CONSTRAINT `score_ibfk_4`
    FOREIGN KEY (`Bowler`)
    REFERENCES `technovert-cup-cricket-tournament`.`player` (`PlayerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
